set echo on
ALTER PLUGGABLE DATABASE PDB1 CLOSE ;
DROP PLUGGABLE DATABASE PDB1 INCLUDING DATAFILES;
!mkdir /u02/app/oracle/oradata/ORCL/pdb1
CREATE PLUGGABLE DATABASE PDB1 ADMIN USER admin IDENTIFIED BY Welcome_1  ROLES=(CONNECT)
  CREATE_FILE_DEST='/u02/app/oracle/oradata/ORCL/pdb1';
alter PLUGGABLE DATABASE PDB1 open;

exit

