set echo on
ALTER PLUGGABLE DATABASE toys_root_dev CLOSE IMMEDIATE;
DROP PLUGGABLE DATABASE robots_dev INCLUDING DATAFILES;
DROP PLUGGABLE DATABASE dolls_dev INCLUDING DATAFILES;
DROP PLUGGABLE DATABASE toys_root_dev INCLUDING DATAFILES;
exit
