set echo on
ALTER PLUGGABLE DATABASE toys_root CLOSE IMMEDIATE;
DROP PLUGGABLE DATABASE robots INCLUDING DATAFILES;
DROP PLUGGABLE DATABASE dolls INCLUDING DATAFILES;
DROP PLUGGABLE DATABASE doodles INCLUDING DATAFILES;
DROP PLUGGABLE DATABASE toys_root$SEED INCLUDING DATAFILES;
DROP PLUGGABLE DATABASE toys_root INCLUDING DATAFILES;
ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE CONTAINER = ALL;
ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE IDENTIFIED BY Welcome_1 CONTAINER = ALL;
ADMINISTER KEY MANAGEMENT CREATE KEYSTORE '/u02/app/oracle/admin/ORCL/tde_wallet' IDENTIFIED BY Welcome_1;
ADMINISTER KEY MANAGEMENT SET KEYSTORE OPEN IDENTIFIED BY Welcome_1 CONTAINER = ALL;
ADMINISTER KEY MANAGEMENT SET KEY IDENTIFIED BY Welcome_1 WITH BACKUP CONTAINER = ALL;
exit
