set echo on
ALTER PLUGGABLE DATABASE test CLOSE ;
DROP PLUGGABLE DATABASE test INCLUDING DATAFILES;
CREATE PLUGGABLE DATABASE test ADMIN USER admin IDENTIFIED BY Welcome_1  ROLES=(CONNECT)
  CREATE_FILE_DEST='/u02/app/oracle/oradata/ORCL/test';
alter PLUGGABLE DATABASE test open;
exit
