set echo on
ALTER PLUGGABLE DATABASE toys_root CLOSE IMMEDIATE;
DROP PLUGGABLE DATABASE robots INCLUDING DATAFILES;
DROP PLUGGABLE DATABASE dolls INCLUDING DATAFILES;
DROP PLUGGABLE DATABASE doodles INCLUDING DATAFILES;
DROP PLUGGABLE DATABASE toys_root$SEED INCLUDING DATAFILES;
DROP PLUGGABLE DATABASE toys_root INCLUDING DATAFILES;
exit
